import { useEffect, useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Plus } from "lucide-react";
import { toast } from "sonner";
import {
  transformGeneratedContent,
  type GeneratedContentData,
} from "@/utils/contentTransform";

type ContentState = "loading" | "empty" | "content";

export default function DailyContent() {
  const { isAuthenticated } = useAuth();
  const [contentData, setContentData] = useState<GeneratedContentData | null>(null);
  const [contentState, setContentState] = useState<ContentState>("loading");

  const { data: learningPath } = trpc.learningPath.get.useQuery(undefined, {
    enabled: isAuthenticated,
  });

  const getTodayQuery = trpc.content.getTodayContent.useQuery(
    { proficiencyLevel: learningPath?.currentLevel || "junior_high" },
    { enabled: isAuthenticated && !!learningPath }
  );

  const generateMutation = trpc.content.generateToday.useMutation({
    onSuccess: (result) => {
      if (!result.success || !result.data) return;
      const normalized = Array.isArray(result.data) ? result.data[0] : result.data;
      setContentData(transformGeneratedContent(normalized));
      setContentState("content");
      toast.success("Today's content is ready.");
    },
    onError: (error) => {
      toast.error(error.message || "Failed to generate content.");
    },
  });

  const addToCardsMutation = trpc.srs.addCard.useMutation({
    onSuccess: () => {
      toast.success("Added to your review cards.");
    },
    onError: (error) => {
      toast.error(error.message || "Failed to add the card.");
    },
  });

  useEffect(() => {
    if (getTodayQuery.isLoading) {
      setContentState("loading");
      return;
    }

    if (getTodayQuery.data?.length) {
      setContentData(transformGeneratedContent(getTodayQuery.data[0]));
      setContentState("content");
      return;
    }

    if (getTodayQuery.isSuccess) {
      setContentState("empty");
    }
  }, [getTodayQuery.data, getTodayQuery.isLoading, getTodayQuery.isSuccess]);

  if (!isAuthenticated) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <p>Please sign in first.</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <div className="container space-y-8 py-8">
        <div className="space-y-2">
          <h1 className="text-3xl font-bold">Today's learning content</h1>
          <p className="text-muted-foreground">
            Daily content is generated by level so you always have a small, focused
            set of material to review.
          </p>
        </div>

        {contentState === "loading" ? (
          <div className="flex items-center justify-center py-12">
            <div className="h-12 w-12 animate-spin rounded-full border-b-2 border-accent" />
          </div>
        ) : contentState === "empty" ? (
          <Card>
            <CardContent className="py-12 text-center">
              <p className="mb-4 text-muted-foreground">
                No content has been generated yet for today.
              </p>
              <Button
                onClick={() => {
                  if (!learningPath) return;
                  generateMutation.mutate({
                    proficiencyLevel: learningPath.currentLevel,
                  });
                }}
                disabled={generateMutation.isPending || !learningPath}
              >
                {generateMutation.isPending ? "Generating..." : "Generate today's content"}
              </Button>
            </CardContent>
          </Card>
        ) : contentData ? (
          <div className="space-y-6">
            {contentData.vocabulary.length ? (
              <Card>
                <CardHeader>
                  <CardTitle>Vocabulary</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  {contentData.vocabulary.map((item) => (
                    <div
                      key={`${item.word}-${item.definition}`}
                      className="border-l-4 border-accent py-2 pl-4"
                    >
                      <p className="text-lg font-semibold">{item.word}</p>
                      <p className="text-sm text-muted-foreground">{item.definition}</p>
                      <p className="mt-2 text-sm italic">Usage: {item.usage}</p>
                      <Button
                        size="sm"
                        variant="outline"
                        className="mt-3"
                        onClick={() => {
                          addToCardsMutation.mutate({
                            frontText: item.word,
                            backText: item.definition,
                            exampleSentence: item.usage,
                            proficiencyLevel: learningPath?.currentLevel || "junior_high",
                          });
                        }}
                      >
                        <Plus className="mr-1 h-4 w-4" />
                        Add to SRS
                      </Button>
                    </div>
                  ))}
                </CardContent>
              </Card>
            ) : null}

            {contentData.phrases.length ? (
              <Card>
                <CardHeader>
                  <CardTitle>Phrases</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  {contentData.phrases.map((item) => (
                    <div
                      key={`${item.phrase}-${item.definition}`}
                      className="border-l-4 border-blue-500 py-2 pl-4"
                    >
                      <p className="text-lg font-semibold">{item.phrase}</p>
                      {item.definition ? (
                        <p className="text-sm text-muted-foreground">{item.definition}</p>
                      ) : null}
                      {item.usage ? (
                        <p className="mt-2 text-sm italic">Usage: {item.usage}</p>
                      ) : null}
                    </div>
                  ))}
                </CardContent>
              </Card>
            ) : null}

            {contentData.sentences.length ? (
              <Card>
                <CardHeader>
                  <CardTitle>Sentences</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  {contentData.sentences.map((item) => (
                    <div
                      key={`${item.sentence}-${item.definition}`}
                      className="border-l-4 border-green-500 py-2 pl-4"
                    >
                      <p className="text-lg font-semibold">{item.sentence}</p>
                      {item.definition ? (
                        <p className="text-sm text-muted-foreground">{item.definition}</p>
                      ) : null}
                      {item.usage ? (
                        <p className="mt-2 text-sm italic">Usage: {item.usage}</p>
                      ) : null}
                    </div>
                  ))}
                </CardContent>
              </Card>
            ) : null}

            {contentData.grammar ? (
              <Card>
                <CardHeader>
                  <CardTitle>Grammar focus</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  <p className="font-semibold">{contentData.grammar.topic}</p>
                  <p className="text-sm text-muted-foreground">
                    {contentData.grammar.explanation}
                  </p>
                  <p className="text-sm italic">Example: {contentData.grammar.example}</p>
                </CardContent>
              </Card>
            ) : null}
          </div>
        ) : null}
      </div>
    </div>
  );
}
